### ISSUE TITLE
Bug TargetTemperature not shown when mode is heatcool

### ISSUE THREAD

**Issue by roswennen** [openhab/openhab-google-assistant#60] opened 2018-11-04 09:08 UTC
There is a bug in the heatcool mode for thermostats. 

The status heatcool is taken correctly but the targettemperature is not taken by google home, target temperature is 0 in Google Home app.

For the modes heat and cool the target temperature is captured and displayed correctly.

See screenshots below, all 3 have exactly the same TaregetTemperature item with same value, only mode is changed and the heatcool one shows 0 as target temp.

![img_0610](https://user-images.githubusercontent.com/26482353/47961735-fd62a880-e010-11e8-8d62-6134f703616b.PNG)
![img_0611](https://user-images.githubusercontent.com/26482353/47961737-02bff300-e011-11e8-8685-6dc61b4a90f0.PNG)
![img_0612](https://user-images.githubusercontent.com/26482353/47961738-05bae380-e011-11e8-81c7-0cff3e250d51.PNG)

**Comment by alibahba** [comment] 2018-12-12 09:04
Duplicate of #35

**Comment by marziman** [comment] 2020-01-07 05:31
Closing

**Closed by marziman** 2020-01-07 05:31 UTC
