### ISSUE TITLE
2FA metadata not working when asking confirmation or pin code

### ISSUE THREAD

**Issue by ozirissp** [openhab/openhab-google-assistant#130] opened 2020-01-17 14:07 UTC
Thanks a lot for the update with metadata, it's awsome ! @michikrug 

I am trying 2FA with tfaPin and tfaAck parameter.

It may be a google server side issue, but I am not able to make it works (I use french language, but also try with english ...)

When I ask to my Google Assistant (after a successful sync),

First test with my system alarm and tfaPin [tfaPin="1234"]

ME : "Enable my system alarm"
Google : "Can I have your security code ?"
ME :  "1234"
Google show me result of a search of 1234 (a song ....) and doesn't enable my system alarm

Second test with a light and tfaAck=true
Me : "Turn on my light"
Google: "Are you sure ?"
Me: "Yes"
Google: "Understood"
(french translated)
But nothing happen ... (the light is still off)

Am I the only one with this issue ?

I try it on my phone and google home mini ...

**Comment by michikrug** [comment] 2020-01-17 14:10
I will run some tests on my installation to check if I can reproduce the behavior

**Comment by michikrug** [comment] 2020-01-17 14:17
On my Google Home Mini & Android Assistant both ACK and PIN is working (German language)

**Comment by ozirissp** [comment] 2020-01-17 15:24
Just did a sample Switch with only metadata :

Switch  Test_TFA_Switch "Test" <light> {ga="Light" [tfaAck=true]}

I have always a bad behavior from google after my answer for acknowledgment (yes or no ...)

It's seems to forget the context of my answer .... The assistant ask me for a confirmation, but handle my answer like a new request.

**Comment by michikrug** [comment] 2020-01-17 15:36
Used the same item definition as you stated.
Synched my devices.
Said "turn on test" and after saying "yes" for the confirmation it turned on correctly.

Are you waiting for the voice input trigger sound after the acknowledge request was announced to make sure to keep the context?

**Comment by ozirissp** [comment] 2020-01-18 08:42
Yes I am waiting for the voice input trigger ... I do not ask neither "Ok Google" for confirmation/pin input ... very strange ... seems to be google assistant related issue ...

See my screenshot (french) - I only use once the "Ok Google" trigger, and google is listening for my answer but did not understand that was my pin ...

![Screenshot](https://user-images.githubusercontent.com/7404696/72661111-d48cc000-39d6-11ea-978b-b3544b3b3833.jpg)

**Comment by Fiftiz** [comment] 2020-01-18 17:16
Juste une idée, mais sans le mot alarme dans l'item et le nom dans l'app google home, c'est pareil ?

**Comment by kandersen01** [comment] 2020-01-20 18:04
> Juste une idée, mais sans le mot alarme dans l'item et le nom dans l'app google home, c'est pareil ?

Could you please stick to english..
I have the exact same issue, but your post doesnt provide much help.

**Comment by ozirissp** [comment] 2020-01-20 20:43
@Fiftiz Same issue with a "test" item with a custom name ... Not related to the word "Alarm".

By the way on my Lenovo Smart Display (smart screen like Google/Nest Home Hub) when I trigger the item with pin TFA from it, it shows me a pin input dialog on the screen. And when I input it by touch, it works ... But If i use my voice to answer, it keeps doing like my answer is a new query ...

I have enabled "Continous conversation" on my assistant settings even if it doesn't support French (english only), no success with or without it.

@kandersen01 do you have the same issue ?

**Comment by kandersen01** [comment] 2020-01-20 22:49
> @kandersen01 do you have the same issue ?

Yes, exactly the same issue..

**Comment by cholawo** [comment] 2020-02-05 22:17
I have the same issue.   Typing the pin code into my nest home display does work, but when speaking the code it says "sorry it looks like that pin is incorrect" and asks for it again, and then treats my saying the pin again as a brand new query.   
Then I changed my pin to 1234, and it did work.   Here's where it gets interesting:   the firebase logs show that when I speak 1235, it seems to send 01235!
`openhabGoogleAssistant - handleExecute - commands: [{"devices":[{"customData":{"deviceType":"action.devices.types.LOCK","itemType":"Switch","tfaPin":"1235"},"id":"ZWaveNode004SDL1000CHYaleConexisL1_DoorLock"}],"execution":[{"challenge":{"pin":"01235"},"command":"action.devices.commands.LockUnlock","params":{"lock":false}}]}]`
I tried it a few times to be sure and I see 01235 each time.   The time I tried it with 1234 it didn't add this extra zero.

**Comment by cholawo** [comment] 2020-02-05 22:20
The above test was speaking to a home mini and a nest hub.   When I speak to my phone, I see in realtime that extra zero appearing and then quickly disappearing as it shows what its interpreting my speech.    My phone then does succeed in unlocking the door.   I think this has got to be almost entirely a google issue then.   I'll post a video of it so you can see what I mean

**Comment by cholawo** [comment] 2020-02-07 08:49
Sorry for spamming, this is it happening on the nest hub—I'll raise it with google (not that I really know where to post it to get their attention!)  [video](https://photos.app.goo.gl/LZ9DN5vDCqCdmxLRA)

**Comment by michikrug** [comment] 2020-02-07 16:43
@cholawo This is super strange... and definitely an issue Google has to solve

**Comment by kandersen01** [comment] 2020-02-07 17:31
It has to be a language issue (again). I just tried. And even though Danish hasn´t worked for long, but the PIN as well as the acknowledge works fine now.

**Comment by cholawo** [comment] 2020-04-02 20:10
Yes in English US it's starting to work now although it's still quite buggy.  I think Google are finally getting their act together!

**Comment by jimtng** [comment] 2020-05-04 03:02
Having the same issue. My tfa code is 7717, and google says  "Setting Volume".

**Comment by michikrug** [comment] 2021-03-19 11:55
As this seems to be not an issue related to this integration but rather a problem on Google's side, I will close this.

Also my tests did not show this behavior.

**Closed by michikrug** 2021-03-19 11:55 UTC
