### ISSUE TITLE
Thermostat example doesn't allow temperature control

### ISSUE THREAD

**Issue by vendetta1987** [openhab/openhab-google-assistant#63] opened 2018-12-02 13:40 UTC
Playing around with this I started by copying the given example to a newly created Openhab .items file. After some fiddling around I manged to get the thermostat to show up in my home application.
Make sure to change the mode item to type string as it was giving errors otherwise.
I'm now able to set the mode via GA but no temperature whatsoever shows up. Changing the mode doesn't help. I added the items to my OH sitemap and was able to control setpoint und current temperature so the basic setup seems alright. If told to set the temperature the assistant tells me it can't as it is unavailable. The plus/minus buttons show up in the app but don't react. I did expose the items to MyOpenhab althought I found it not to be necessary for GA specific stuff (eg lamps which are working fine).  I even installed the homekit addon in OH although it shouldn't be necessary, no change.
Any help would be appreciated as I'm out of ideas by now.

My slightly changed itmes file:
`Group gThermostat "Thermostat" [ "Thermostat" ]
String Thermostat_Mode "Heating/Cooling Mode" (gThermostat) [ "homekit:HeatingCoolingMode" ]
Number Thermostat_Temp "Temperature" (gThermostat) [ "CurrentTemperature" ]
Number Thermostat_Setpoint "Setpoint" (gThermostat) [ "TargetTemperature" ]`

**Comment by velaar** [comment] 2018-12-11 17:59
Shouldn't ```String Thermostat_Mode "Heating/Cooling Mode" (gThermostat) [ "homekit:HeatingCoolingMode" ]``` be a number? 


here is a working example: 

```
Group gEntranceThermostat "Entrance Thermostat" [ "Thermostat" ]
Number num_Entrance_Temperature "Entrance temperature" (gEntranceThermostat, gThermostat, gInflux) [ "CurrentTemperature" ] { channel="zwave:device:512:node3:sensor_temperature" } 
Number num_Entrance_Setpoint "Entrance setpoint" (gEntranceThermostat, gThermostat, gInflux)  [ "TargetTemperature" ] { channel="zwave:device:512:node3:thermostat_setpoint_heating" } 
Number num_Entrance_Operating_State "Entrance operating state" (gEntranceThermostat, gThermostat, gInflux) { channel="zwave:device:512:node3:thermostat_state" }
Number num_Entrance_Mode "Entrance operating mode" (gEntranceThermostat, gThermostat, gInflux) [ "homekit:HeatingCoolingMode" ] { channel="zwave:device:512:node3:thermostat_mode" }
```

**Comment by alibahba** [comment] 2018-12-12 08:50
Thermostat mode [ "homekit:HeatingCoolingMode" ] can be a number or a string but when you want to change the mode it must be a string.
Number values are translated to google accepted mode values (string).
What's going wrong is that in the auto mode google needs 2 setpoints, 1 for heating and 1 for cooling.
Maybe next Christmas holidays I will make some time to solve this.

**Comment by alibahba** [comment] 2018-12-12 09:03
Duplicate of #60

**Comment by marziman** [comment] 2018-12-12 12:33
@alibahba i will close this, since we have aready an issue for this.

Let me know if you re going to tackle this. Thanks!

**Closed by marziman** 2018-12-12 12:33 UTC
