### ISSUE TITLE
Thermostat does not work anymore

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-google-assistant#92] opened 2019-05-26 16:00 UTC
After the last cloud deploy, Thermostast items defined according to the documentation cannot be used anymore from Google Assistant.
Several users are experiencing this issues as reported on the community, for example:
https://community.openhab.org/t/official-google-assistant-integration-for-openhab/40425/879
https://community.openhab.org/t/google-assistant-thermostat-issue/74920
https://community.openhab.org/t/thermostat-not-responding-on-google-assistant-ga/75057
https://community.openhab.org/t/openwebnet-thermostat/74851/

Problem is most probably with the GA cloud function and not with things/items definitions or bundles as the problem is reported no matter of the binding used.

## Expected Behavior
GA can read temperature, set temperature and change mode like before last cloud update. Both Mode items defined as Numbers and String should be supported.

## Current Behavior
GA cannot use anymore Thermostat items: "cannot connect" from GH app.

## Possible Solution
Changing tag from `homekit:HeatingCoolingMode` to `HeatingCoolingMode` makes the Thermo sevice usable again from GA, however mode cannot be changed.

## Steps to Reproduce (for Bugs)
1. Define one Thermostat group item and sub-items according to the docs and connect to GA
2. GA cannot connect/use the Thermostat device 
3. change tag to `HeatingCoolingMode` 
4. thermostat can be used but mode cannot be changed (for example to OFF)

## Your Environment
* Version used: OH 2.4 but also 2.5M1

**Comment by pythen** [comment] 2019-05-26 20:04
Hi @mvalla,

I checked all my commits with previous version my first commit.
I found two changes in the thermostat area.

Left side is older version from 25.10.18 | Right side is the last commit
![Bildschirmfoto vom 2019-05-26 21-37-13](https://user-images.githubusercontent.com/345872/58386431-1e680680-8000-11e9-903b-229949f00513.png)

![Bildschirmfoto vom 2019-05-26 21-37-56](https://user-images.githubusercontent.com/345872/58386504-de555380-8000-11e9-8bdc-f7662436539d.png)

I do not think it's because of these changes.

But I found a line in the source code that does not seem to be right.
![Bildschirmfoto vom 2019-05-26 21-38-34](https://user-images.githubusercontent.com/345872/58386551-a995cc00-8001-11e9-93bf-e5fa6ebbdbae.png)

There was always a semicolon missing at the end of the line in this line. (Row 230)
Due to a misadjustment of my development environment there was still a space at the end of the line, maybe that's the mistake.

I hope it helps.

**Comment by ElCheekytico** [comment] 2019-06-15 17:02
I am having the same issue. I removed "homekit:" from the tag and I am able to connect to the thermostat with the Home app and control the temp.

@marziman Have you had a chance to look into this? Thanks.

**Comment by xtremeIX** [comment] 2019-06-22 18:01
@marziman I am also having this issue and am curious if you were able to resolve this it...

**Comment by cweitkamp** [comment] 2019-06-22 18:30
> I emoved "homekit:" from the tag and I am able to connect to the thermostat with the Home app and control the temp.

This proposal is working for me too. I am able to change the temperature again without GA complaining. But using the thermostat mode is not possible anymore. That is a regression. Would be nice to see it fixed before winter will come.

**Comment by Fiftiz** [comment] 2019-06-25 07:05
Same here, there is a problem with the homekit in the tag :/ .

**Comment by FredericMa** [comment] 2019-06-25 09:08
+1

**Comment by lucacalcaterra** [comment] 2019-06-27 08:12
Removing homekit: tag works for me too !

**Comment by achille2k** [comment] 2019-07-13 09:22
Me too!  mode cannot be changed

**Comment by kandersen01** [comment] 2019-08-05 20:56
I believe Google has changed alot regarding the thermostat, mode and current temperature.. 
I have several issues which no longer seems to be like the docs are saying.. 

Fx. I have a openhab item which only has the tag ["CurrentTemperature"]. Its not part of any thermostat group, just plain and simple temperature sensor.  But in the Google Home app, it´s showen as it was a thermostat with heating mode.. Ie I can change the setpoint, which makes no sense, since this is just a temperature sensor.

On my Google Nest Hub (former named Home Hub). No thermostats seems to work. All respond with "mode not supported". The current temperature comes through fine though.. 

For speech - I can controle the thermostats like I used to. It seems like this is only visual changes in the Home app as well as the Google Nest Hub. 

I think this call for a "new going through whatever Google may have changed", cause something had changed for sure, and it´s not my setup. It has been the same for a very long time, (since openhab start supporting Google Assistant).

**Comment by robtop100** [comment] 2019-09-01 19:35
Hi, any update in Google Assistant integration and NOT WORKING:
[“homekit:TargetHeatingCoolingMode”] vs [“homekit:HeatingCoolingMode”] ?
We can set target temperature, read target temperature, read humidity but we cannot set heatingCooling mode… so we don’t know what is current mode in specific room …

**Comment by Fiftiz** [comment] 2019-09-09 17:58
there is news, or finally no solution ?

**Comment by mroussel** [comment] 2019-09-10 12:00
This is very annoying, is there any fix ? Thanks

**Comment by skimdankish** [comment] 2019-09-10 12:49
I have been running a fork for some time, I will look side by side to see if I can spot it.  Unfortunately, I don't have the time to get into full on debugging.

I believe the original reason for the HomeKit tags was to conform to Openhab HomeKit binding and keep consistency across bindings, so I kept in when I took a stab at the thermostat functionality a while back.

**Comment by hotrodwinston** [comment] 2019-10-19 02:12
What happens if you set your thermostat to auto mode and issue GA commands like "set cooling to xx" or "set heating to xx" ? Will it adjust only the setpoint you ask it to?

**Comment by kandersen01** [comment] 2019-10-19 15:35
Using GA commands to change the setpoint or ask for the temperature, works fine for me. 
My issue is, it shows "not supported mode" on the Google Nest Hub, but show fine on the Google Home app. (android).

**Comment by robtop100** [comment] 2019-10-20 09:20
"What happens if you set your thermostat to auto mode and issue GA commands like "set cooling to xx" 
I cannot use those commands - response from GA: it looks like openHAB isunavailable right now"
but I can use "set kitchen thermostat to [number]"
"My issue is, it shows "not supported mode" on the Google Nest Hub" -I don't have nest hub

**Comment by robtop100** [comment] 2019-10-20 09:24
my sample thermostat config:
Group  gUpperBathroom_Thermostat   ["Thermostat"] 
String bathroom_mode 	["homekit:TargetHeatingCoolingMode"]
Number bathroom_tt 	["TargetTemperature"] 
Number bathroom_ct	["CurrentTemperature"]
Number bathroom_h	["CurrentHumidity"]

**Comment by michikrug** [comment] 2019-10-25 00:13
I hope this will be fixed with my incoming PR.
Afterwards we should not use the "homekit:" prefix anymore.

**Comment by kandersen01** [comment] 2019-10-25 16:23
Thanks alot michikrug

**Comment by hotrodwinston** [comment] 2019-10-27 00:13
Has the pull request been merged?

**Comment by hotrodwinston** [comment] 2019-11-03 22:39
> my sample thermostat config:
> Group gUpperBathroom_Thermostat ["Thermostat"]
> String bathroom_mode ["homekit:TargetHeatingCoolingMode"]
> Number bathroom_tt ["TargetTemperature"]
> Number bathroom_ct ["CurrentTemperature"]
> Number bathroom_h ["CurrentHumidity"]

Is this working for you? If not have you tried the removal of the homekit tag as suggested in this thread?

**Comment by robtop100** [comment] 2019-11-04 14:31
@hotrodwinston 
I can set ["TargetTemperature"] to specific value
I can read current temperature i humidity.
but..I cannot set HeatingCooling mode - it is constant value "heating mode"
It is similir results when I am using or not ""homekit" prefix
I am using OH version 2.4

**Comment by sidamos** [comment] 2019-11-22 07:57
There seems to be a new issue after recent Google Home app updates. I had removed the Homekit tag during initial integration and it was working fine for me. But now it shows "Other" instead of the set temperature (and I cannot change it) and also it shows "Other mode". Actual temperature still works.

**Comment by kandersen01** [comment] 2019-11-24 16:18
@sidamos 
Issue have been confirmed. If you´re using "Fahrenheit" it will breake your thermostat in Google Home app. 
See more at #126

**Comment by sidamos** [comment] 2019-11-24 16:27
@kandersen01 I am not using Fahrenheit.

**Comment by kandersen01** [comment] 2019-11-25 13:12
@sidamos okay, that was my next suggestion :-)

**Comment by marziman** [comment] 2020-01-07 05:41
I am closing this. Please lets create a new issue if needed.

**Closed by marziman** 2020-01-07 05:41 UTC
