### ISSUE TITLE
Inverted OPEN/CLOSE Blinds

### ISSUE THREAD

**Issue by ozirissp** [openhab/openhab-google-assistant#82] opened 2019-05-17 07:11 UTC
Since fix #59 by @pythen, we can control Blinds from Google Assistant.

But with my setup, I have to ask OPEN to close my blinds, and CLOSE to open it ... I am having this issue because I have invert_percent=true on my blinds (OpenZwave Channel). I need this parameter for the correct state of my binds.

In my case, my Blind Item :
0% = OPEN
100% = CLOSE

But from Google Assistant asking OPEN Blind set my Item to 0% (close state for me)

**Comment by magd1978** [comment] 2019-05-17 07:30
Hi.
I just tried the integration of the blinds with Google Home (Spanish version) and I found an incongruity. For openHab, opening a blind is setting it to 0%. But when asking Google Home to open a blind the received command is 100% (the procentage indicates the opening value instead of the closing value). It can be fixed via openHab rules, but it does not seem like a very elegant solution.
I believe that the translation of the values ​​should be done by the openHab connector, whether a command is sent from Google Home, or if an update of the value is reported from openHab. And already put to ask, it would be interesting that you could set some parameter that indicated to the connector whether it must to translate the corrected values ​​0% and 100% to UP / DOWN commands, for bindings that do not support percentages. This parameter could be an additional label such as "UpDownOnly" or "NoPercentage".

**Comment by pythen** [comment] 2019-05-17 09:27
@magd1978 
Great idea, I implement the labels at weekend.

**Comment by magd1978** [comment] 2019-05-17 09:49
@pythen
> UpDownInvert = Send inverted values
That would also be very good. And in reference to that, I think that the current behavior (percentage of opening) should be considered as "inverted value", since, as indicated before, the data model used in openHAB considers the opposite (closing percentage).
Thanks!

**Comment by pythen** [comment] 2019-05-17 19:38
@magd1978 
I think the problem is the many different configurations that need to be handled now
The Google Assistant also supports other directions, such as just up and down

I have now found something that can save us a workaround on the item name.

via metadata
`
Rollershutter Roll_OG_Media "Rollladen" <rollershutter> ["Blinds"] {channel="zwave:device:xxxxxxx:node7:blinds_control", googleassistant="shutter" [ direction="UpDown", invert=true, percent=true ]}
`

I implement this at weekend

**Comment by magd1978** [comment] 2019-05-17 20:02
@pythen
Perfect.  Instead of using tags, what you propose is to configure the Google Home connector as any binding in the item.  Is that?

**Comment by mvalla** [comment] 2019-05-17 20:02
You should be careful in giving too many options here.
I think the semantics are pretty clear and the Google Assitant connector should just do the right translation from the Google assistant up/down semantics <-> semantics of openHAB. 
Giving the option here to invert commands will just confuse users. 
Once the translation is correct , monibvert option should be needed anymore.
And if’s needs then it is the binding that is wrong.

**Comment by magd1978** [comment] 2019-05-17 20:23
I agree that it is best to simplify so as not to confuse users.  However, as an advanced user, I appreciate all possible customization options.
I propose that, as you say, the connector will work by default with the values ​​defined in the default semantics of openHAB (UpDown function, up = 0%, down = 100%), and optionally have these options to change the type of movement, to invert the values ​​with respect to the openHAB standard and to send UP / DOWN commands instead of percentages.

**Comment by dominikkv** [comment] 2019-05-17 20:37
Hmm I just wonder whether this should be solved using [profiles](https://www.openhab.org/docs/concepts/profiles.html). Another docu [here](https://www.openhab.org/docs/configuration/items.html#profiles).

**Comment by Tihmann** [comment] 2019-05-18 07:43
I also tried it in German. With my Loxone installation if you to say OPEN ("Öffne") to close and vice versa.

**Comment by marziman** [comment] 2019-05-29 12:08
Duplicate. This is fixed. I am closing this.

**Closed by marziman** 2019-05-29 12:08 UTC
