### ISSUE TITLE
Routines to turn On/Off lights cause google to reply "Sorry, I'm unable to reach X" 

### ISSUE THREAD

**Issue by velaar** [openhab/openhab-google-assistant#44] opened 2018-07-31 19:49 UTC
Was not able to find any way to diagnose/correct this. Found a few [mentions](https://community.openhab.org/t/official-google-assistant-integration-for-openhab/40425/237?u=velaar) of it on OH forums.
 
Some notes:
- Google is able to determine state of the lights (I can ask "Which lights are on" and it works correctly)
- The reply is "Sorry I am unable to reach <first item in the list> right now. Sorry I am unable to readh 20 items right now. Please try again", So it seems to make 2 requests. 
- This happens even if only one switch/item is in the routine

**Comment by LucasMcQ** [comment] 2018-08-15 17:49
I am also having this issue with my Sengled element classic light bulbs. The lights will turn on after my routine is executed, but it will still say the "Sorry, I'm unable to reach X" error message.

**Comment by LucasMcQ** [comment] 2018-08-15 18:59
I found a work around for this. If you make a custom routine, and then in the commands you say "Turn on all lights" it will do so without giving that error message.

**Comment by velaar** [comment] 2018-08-21 20:11
I tried to pull the logs from my Android phone but didn't find anything interesting. It seems ti diagnose this I'll have to recreate the environment on my google account. Not sure if @marziman can look into this from myopenhab.org side.

**Comment by alibahba** [comment] 2018-08-31 18:50
Today I have done some debugging for this issue on my own integration.
it's weird. When executing a routine from google assistant the request is exactly the same as when I say "turn kitchen light on". The execution works fine and no errors occurred at the integration. I'm not able to detect in the request if the execution is from a routine or from a single phrase. This could be a bug at Google's side.

**Comment by alibahba** [comment] 2018-09-05 20:17
@velaar No, Openhab receives only 1 execution request, exactly the shame when you turn that light on or off. OpenHab is not the only one with this issue:  [here](https://productforums.google.com/forum/#!topic/googlehome/sxDw6YWvNkcl) and [here](https://productforums.google.com/forum/#!topic/googlehome/z6XiqoFlB5o) users are reporting the same issue.
OpenHab is not logging the states of the items active to the google home graph (google has to query OpenHab for the current state). Maybe google is waiting for a response i homegraph.
@marziman i hope you have some contacts by google where you can ask this question.

**Comment by avk999** [comment] 2018-10-23 17:42
> I found a work around for this. If you make a custom routine, and then in the commands you say "Turn on all lights" it will do so without giving that error message.

But you'll get "You've got it, turning XXX on" or similar when you call the routine.

**Comment by avk999** [comment] 2018-10-23 17:44
Same issue with Tasmota plug with myopenhab and google assistant. Can provide logs etc if it can help.

**Comment by gilbertococchi** [comment] 2018-10-24 13:34
Can somebody share logs on both OpenHab2 and/or Assistant on Google App if running locally?

**Comment by avk999** [comment] 2018-10-24 13:39
Sorry, I'm using myopenhab cloud to integrate with google. Can share from
my openhab instance and google app on Android.

**Comment by 3cky** [comment] 2018-10-24 21:01
[Here is a log in JSON format](https://github.com/openhab/openhab-google-assistant/files/2512250/openhab-ga-local.log) obtained from my local openhab-google-assistant Google App instance after the next commands ran:

1) Light switched on/off in Google Home app (no errors were indicated)
2) Light switched on/off by routine ("Sorry, I'm unable to reach light right now" response)
3) Light switched on/off by Googe Home Mini voice command "Switch light on/off" ("OK, you got it" response)

Honestly, I can't see much difference between log records for those invocations. BTW, I'm living outside US and routines are still unavailable in my country, so I switched my phone locale to US to enable this functionality. It looks like Google just don't like that I'm using routines with OH.

**Comment by soloam** [comment] 2018-10-25 12:33
I also live outside the US, but I visit the US often, I tested the routines in and outside the US, with my phones and homes always on location US, and I always get the same errors

**Comment by abedwardsw** [comment] 2018-11-09 16:55
I am also still getting this issue.   Is there any debugging I can provide?   I am using myopenhab so I don't have my own instance and therefore cannot easily get any type of debug logs.  Just wondering how I can help troubleshoot this issue.

**Comment by soloam** [comment] 2018-11-09 18:44
Yes this still happens, I only have devices working from openhab, so I don't know if this is a problem from openhab side or Google!

**Comment by ntk9** [comment] 2018-12-11 15:59
I also having this problems with routines and scene only

**Comment by velaar** [comment] 2018-12-11 18:04
The issue is definitely still there. However, it seems I've just discovered a new or related one. In order to not spam the 'issues' tab. I'll put it here for the moment.
 
The following query: 
"Ok Google, Set all thermostats to 22 degrees" causes GH to think for a while and then say "Sorry, I couldn't reach OpenHab" BUT the action itself is completed. OH does receive the command. 

@3cky if you still have your private cloud instance, can you test it, please? 

It also seems that all attempts to summon @marziman to this issue have failed.

**Comment by marziman** [comment] 2018-12-11 18:37
Let me see if I can help. Need to reproduce. Sorry, I was busy with other stuff.

**Comment by 3cky** [comment] 2018-12-11 18:38
@velaar yes, tested your query with my private cloud instance and it seem to work. OH does receive the command and Google Home reported the successful thermostat setpoint change  ("Sure, setting the thermostat to 22 degrees").

**Comment by velaar** [comment] 2018-12-11 18:41
> @velaar yes, tested your query with my private cloud instance and it seem to work. OH does receive the command and Google Home reported the successful thermostat setpoint change ("Sure, setting the thermostat to 22 degrees").
@3cky 
Was the command to set _All_ thermostats? (As in more than one at the same time) Because with just one it works well for me too.

**Comment by 3cky** [comment] 2018-12-11 20:32
@velaar yes, I issued the command exactly as you wrote it. But I have only one thermostat set up in OH though.

**Comment by gilbertococchi** [comment] 2018-12-12 14:06
@marziman also when performing Light Switching action changes via Routines the issue is completed but for every OH Item to change the status Google Home replies with the message "Sorry I am un able to reach Device X".
I am not sure if the issue is on the Google side still, will continue to investigate.

**Comment by pytz** [comment] 2018-12-26 14:20
Same problem for me. Any updates on this issue?
I would like to control my roomba which is connected via Openhab.

So i have an item named "robot go" which will be used in a rule.
When I say "turn robot go on" it works without any error.
When I create a routine with command "start cleaning" and add only "robot go" as item to be switched the result is "Sorry I am unable to reach robot go". Nevertheless the state of the item is switched.
I also tried editing the predefined "good night" routine but with the same result.

Also it doesn't matter whether I use my phone or Google Home to trigger the routine.

**Comment by RestOp** [comment] 2019-01-02 18:00
I have the same Problem but not with the rutines, but with normal commands like "turn on office lamp"!
It seems like after time (10-20 minutes) of inactivity openHab or Google goes in sleep and after this it can not react fast on command. It says "It looks like openHAB is unavailable right now" but after 10-50 seconds it turn the lamp! If i say immediatly after tis command "turn off office lamp" is works very fast then  "turn on office lamp" it works fast again.
Also i can reproduce this action if i open Google Home on smartphone and open my room with this lamps it shows a long time under the Lamps - Connection... and the Can't connect...
After few tries it works, but it can be so...

**Comment by RestOp** [comment] 2019-01-02 18:00
> Let me see if I can help. Need to reproduce. Sorry, I was busy with other stuff.

I have the same Problem but not with the rutines, but with normal commands like "turn on office lamp"!
It seems like after time (10-20 minutes) of inactivity openHab or Google goes in sleep and after this it can not react fast on command. It says "It looks like openHAB is unavailable right now" but after 10-50 seconds it turn the lamp! If i say immediatly after tis command "turn off office lamp" is works very fast then "turn on office lamp" it works fast again.
Also i can reproduce this action if i open Google Home on smartphone and open my room with this lamps it shows a long time under the Lamps - Connection... and the Can't connect...
After few tries it works, but it can be so...

**Comment by fab33** [comment] 2019-01-03 21:57
Same problem here with french settings. Items change but GH say it can't reach for every devices.

**Comment by soloam** [comment] 2019-01-03 22:38
I would like to understand if the problem is set to the openhab or with the Google

**Comment by marziman** [comment] 2019-01-06 23:37
I think I will make an E2E test. I need to re-setup some thingsbto reproduce it. So I hope I can test it the coming days. I will get back if I ve infos. It might be that Google has a bug. But lets first verify.

BR Mehmet

**Comment by RestOp** [comment] 2019-01-08 10:09
> I would like to understand if the problem is set to the openhab or with the Google

Hard to say. For Example i have Broadlink with 22 Lamps and some rutines, use it also with Google. I have **never** had such problem.

Let us wait till Mehmet verifies it.

**Comment by alibahba** [comment] 2019-01-08 12:10
> Hard to say. For Example i have Broadlink with 22 Lamps and some routines, use it also with Google. I have **never** had such problem.

I guess the problem is related to the not implemented report state functionality.

**Comment by fab33** [comment] 2019-01-09 16:43
when using Assistant on my phone with text entry for routine, Google Assistant answer me it can't establish connexion with openHAB and openHAB is nat avaiable at the moment. But the routine works !

**Comment by d-sko** [comment] 2019-01-31 05:53
Hi, I have the same problem: Openhab with some Ikea Tradfri lights, Google Assistant set up with myopenhab, routines are working fine but I'm getting the error "I'm sorry, I can't reach x lamps" (I'm using it in german, the original message is "Es tut mir leid, ich kann x Lampen aktuell nicht erreichen.")

**Comment by phil2fer** [comment] 2019-03-10 19:53
Hi, same problem here with french google home mini

**Comment by brookb52** [comment] 2019-04-19 13:00
I too have the same problem. " it looks like openhab is unavailable right now " . Sometimes after saying this it honours my command anyway but mostly i have to repeat myself 3 or 4 times before it will honour my voice commands and reply with " ok, turning the foo bar light/s off". Only happens in the evenings but never in the mornings. Looks like it could be a load issue either with the openhab or Google servers?

**Comment by jlwainwright** [comment] 2019-05-08 21:49
Same issue here. Does it with all routines. Is this a regional thing? I am in South Africa.

**Comment by RayBa82** [comment] 2019-06-17 09:49
Seems like the response send back to Google is not correct when you execute a rule. I have written my own google cloud action for openhab based on the official google smarthome samples and this repository and it works flawless without this annoying error.

**Comment by jlwainwright** [comment] 2019-06-17 10:29
Willing to share @RayBa82?

**Comment by RayBa82** [comment] 2019-06-17 19:57
https://github.com/RayBa82/openhab-assistant

Not sure if it still runs in google app engine, I run it on my own server in docker.

**Comment by hotrodwinston** [comment] 2019-06-19 21:48
Any possibility of getting the fix from @RayBa82 included in openhab main?

**Comment by ConfusedTA** [comment] 2019-09-19 08:48
I've just set up a switch in openHAB to open/close my garage door, and have set up a Routine so I can say "open the garage door" and "close the garage door", as opposed to "turn garage door on".

The command is executed by openHAB within a second, but I get "I can't reach the garage door right now" as a response from GA.

But, if I do say "turn garage door on", I get "Ok, turning on the garage door", so it looks like it's something to do with routines only?

**Comment by RestOp** [comment] 2019-09-19 08:53
Thread is one year old and google make nothing with it. Just drop ur Google Speakers in waste bin!

**Comment by RayBa82** [comment] 2019-09-19 09:13
Why should google make anything? Its a problem in this addon, my version is running fine and stable without any errors.

**Comment by RestOp** [comment] 2019-09-19 09:15
> Why should google make anything? Its a problem in this addon, my version is running fine and stable without any errors.

Witсh one do u have?

**Comment by RayBa82** [comment] 2019-09-19 09:34
My own tailored for me

**Comment by RestOp** [comment] 2019-09-19 09:39
Maybe u can share or give an advise how to fix the problem if it works stable?

> My own tailored for me

**Comment by RayBa82** [comment] 2019-09-19 10:38
I dont want and dont have time to analyze the errors in this repo, since here is almost zero activity anyway.
I provided the github sample to a working implementation anything else is up to the guys here.

**Comment by gytisgreitai** [comment] 2019-09-23 10:07
> I've just set up a switch in openHAB to open/close my garage door, and have set up a Routine so I can say "open the garage door" and "close the garage door", as opposed to "turn garage door on".
> But, if I do say "turn garage door on", I get "Ok, turning on the garage door", so it looks like it's something to do with routines only?

@ConfusedTA  afaik the correct way  this should be done is by using `action.devices.types.GARAGE` device and `action.devices.traits.OpenClose` trait, which is not supported here.

> I provided the github sample to a working implementation anything else is up to the guys here.

@RayBa82 nice changes, code is more clean and neat with all those es6 features and typescript, congrats on good work. Can you elaborate a bit more on your changes? Afaik you get a better state sync  by using  Home Graph ? Are you will to accept PR for new features like `Volume`, `Alarm`, `MediaState`  since this repo is probably a bit stale...

**Comment by RayBa82** [comment] 2019-09-23 12:14
Using Homegraph adds some nice features. For example: Google recognizes the room you are in and interprets the voice commands if you say "Switch off the lights". Then only the lights in the same room are controlled

The version i am using is not public and a little bit more advanced, I have already added support for Vacuum devices. If you want to use this version I should update the github repo first, but of course I will accept PRs.

But I am converting at the moment to a spring boot app, since i hate js and typescript :-)
Java has a clear Typesafe API and Kotlin is just a dream ;-)

**Comment by marziman** [comment] 2019-10-01 20:16
Ok guys,

I am back on this. I really like what @RayBa82 did with TypeScript as I hate the type unsafety of JS.
So I will squeeze that in and plan for a bigger update with most of the new traits, also for the scenes.

Please hold tight, as I got my setup back up and running tonight.

From now on I also want you guys to be more involved and will try to share how you could be involved more into new features. So all volunteers are welcome. But keep in mind it is some work and needs time.

Thanks and BR
MEhemt

**Comment by marziman** [comment] 2019-10-01 20:17
> I dont want and dont have time to analyze the errors in this repo, since here is almost zero activity anyway.
> I provided the github sample to a working implementation anything else is up to the guys here.

Hmm, sounds strange to me. You could also make a PR, but prefered to make a copy of this repo and use TypeScript. The better approach is to join forces. Not blaming you, just trying to bring things together.

**Comment by marziman** [comment] 2019-10-01 20:20
> > I've just set up a switch in openHAB to open/close my garage door, and have set up a Routine so I can say "open the garage door" and "close the garage door", as opposed to "turn garage door on".
> > But, if I do say "turn garage door on", I get "Ok, turning on the garage door", so it looks like it's something to do with routines only?
> 
> @ConfusedTA afaik the correct way this should be done is by using `action.devices.types.GARAGE` device and `action.devices.traits.OpenClose` trait, which is not supported here.
> 
> > I provided the github sample to a working implementation anything else is up to the guys here.
> 
> @RayBa82 nice changes, code is more clean and neat with all those es6 features and typescript, congrats on good work. Can you elaborate a bit more on your changes? Afaik you get a better state sync by using Home Graph ? Are you will to accept PR for new features like `Volume`, `Alarm`, `MediaState` since this repo is probably a bit stale...

Interesting! Beside TypeScript and some small changes it relies heavily on the structure of this project. But still: Everybody is free to use the other repo if it fits their needs better.

But lets not play:
GA Integration (this repo) is fine, when it has all features you want and wish
AND GA Integration is shitty when it is not up to your wishes.

Just join the efforts and make a PR, it will be highly welcome.

**Comment by meingraham** [comment] 2019-10-14 18:50
I have had a working environment for several months. It seems something has changed over the weekend. We returned from a trip and we are now receiving this error. I do not use Google Assistant routines.

openHAB 2.5.0~S1687-1 (Build #1687) running on RPi 3B (Raspbian Stretch)
No changes from when we left to when the problem began to occur.

Mike

**Comment by hotrodwinston** [comment] 2019-10-14 21:19
@meingraham
Have you tried telling your Google home to "sync all devices"? Issue that command twice and it should fix any "cannot connect to openhab" aside from routines. If that does not work try rebooting your openhab controller and making sure it connects to the internet and that you can control it from myopenhab.org

**Comment by meingraham** [comment] 2019-10-14 21:38
It's not the "cannot connect to openHAB" error. The error is "Sorry I can't reach <device> right now"... but it actually completes the action anyway.

I'm not having a problem with the cloud connector (myopenhab) connecting to my openHAB server.

I went ahead and perform sync devices twice. No effect.

Mike

**Comment by kpanchen** [comment] 2019-10-15 02:27
> It's not the "cannot connect to openHAB" error. The error is "Sorry I can't reach right now"... but it actually completes the action anyway.
> 
Same here, action performed but reply is the same as yours.

**Comment by kpanchen** [comment] 2019-10-15 02:28
> From now on I also want you guys to be more involved and will try to share how you could be involved more into new features. So all volunteers are welcome. But keep in mind it is some work and needs time.
> 
> Thanks and BR
> MEhemt

Willing to help, let us know what we can do!

Thanks for all your work!

**Comment by Dopeyr** [comment] 2019-10-15 09:39
This has started recently for me too when controlling lighting. Some more info: If I specify the individual light, it works but I get "Sorry I can't reach right now" as other people have seen. 

However, if I just say "Turn off the lights", it works and I *don't* receive the "can't reach" message. My lights are assigned in a "Living room" room in Google Home, the same location as the home hub.

**Comment by arduino-cyberspace** [comment] 2019-10-19 09:55
Just wanted to add to this issue: I have had the exact same problem since a week or two ago. Fully working configuration, no changes, and all of a sudden "Sorry, I can't reach [item name] right now, please try again" - but the [item name] gets switched on. 

If I however want to switch it **off**, it works fine without any comments about not reaching it. So both ways work from a technical point of view (switches the [item name] on/off) but switching **on** is getting the faulty response from Google Home (Google Assistant). The same from my Android phone (so this is not specific to Google Home).

Nothing in the OH logs that tells my something outside the normal behaviour.

**Comment by marziman** [comment] 2019-10-19 10:43
@ALL & @kpanchen:

I will investigate this deeper and try to correct.

I am prepare a plan whats need to be improved as base so we can coordinate efforts and you guys can support.

Maybe this one can be fixed within those efforts

**Comment by meingraham** [comment] 2019-10-19 12:07
@arduino-cyberspace

Yes, exactly this. Thanks for adding the detail about on vs. off. And yes, it is Google Assistant regardless of what device initiates the request - home voice assistant or mobile device.

Mike

**Comment by gytisgreitai** [comment] 2019-10-19 12:23
Afaik the problem is here https://github.com/openhab/openhab-google-assistant/blob/a5d15b675b656db07de278114bbc467977091bd3/functions/openhab.js#L310-L315

Upon executing action, this code returns only Success without the actual state as recommended in the docs https://developers.google.com/assistant/smarthome/traits/onoff#device-commands

So without the returned state, google might hit the query endpoint to check what is going on, and if it returns the non changed value (e.g. you asked for OFF, OFF command was sent, but openhab is still ON because e.g. there was some delay and the item state is not yet populated on openhab) you will get the response like this. 

Because for example with https://developers.google.com/assistant/smarthome/traits/armdisarm#device-commands Google will fail every time if you don't return the new value with execute request.

OH, Android, etc logs won't show you anything, instead logs of this code in Google Stack Driver should be investigated

The one way to verify if my assumption is correct   be to create a dummy item (without any actuakl device wired up which can result in delay) and check if it's the same e.g.

`Switch SwtichTest "Test Light" ["Switchable"]`

**Comment by arduino-cyberspace** [comment] 2019-10-19 14:20
Hi,
tested with a dummy "Test light" - exactly the same result. Complaining when switching ON but no problem switching OFF.

**Comment by darrenDST** [comment] 2019-10-21 15:12
hi guys, 

I'm getting the same problem with my Google Assitant's (Home, Mini) when using my Lightwave RF lighting and electrical system which was working perfectly with Google Assistant before.

I've made a post on the Google forum here: [](https://support.google.com/assistant/thread/17350091?hl=en)

**Comment by eeyepee** [comment] 2019-10-23 19:55
Same problem here, switches can be switched on but the response ruined my entire home setup, it's really annoying, I wish if I have enough knowledge to support you guys here. 

Keen to see the issue solved very soon.

**Comment by costascontis** [comment] 2019-10-24 18:08
just the same issue begun 2 weeks ago for me.No problem when turning off but "sorry,i'm unable to reach X" response.Command is working but the wrong response is very annoying,hope for a fix soon!

**Closed** 2019-10-24 19:50 UTC

**Comment by eeyepee** [comment] 2019-10-24 19:55
Hi @marziman, now you merged it with the master, can you tell here when and how will this will take effect?

**Comment by marziman** [comment] 2019-10-24 19:57
Just now deploying, effective in next 30min.

**Comment by meingraham** [comment] 2019-10-24 20:25
Does this require any updates to my openHAB server?

**Comment by eeyepee** [comment] 2019-10-24 20:51
> 
> 
> Just now deploying, effective in next 30min.

Assuming that the merge is already deployed, now not sure if this is related but my Google assistant and Home Mini can't reach my openHAB server.

**Comment by marziman** [comment] 2019-10-24 20:54
Yes I have also problems. Not sure why this happened.

**Comment by marziman** [comment] 2019-10-24 21:08
Ok my GA app is going crazy, I cant resync on app.
Anyone else maybe who can also help testing?

**Comment by hotrodwinston** [comment] 2019-10-24 21:08
To those still having issues - have you issued a "sync my devices" command?

**Comment by marziman** [comment] 2019-10-24 21:08
> Does this require any updates to my openHAB server?

No

**Comment by marziman** [comment] 2019-10-24 21:10
I ve applied one more deployment as there was a URL piece missing. Shall be back working, but my app is broken. Can you please help testing and let me know if the issue here is fixed?

**Comment by Alacard** [comment] 2019-10-24 21:12
> Ok my GA app is going crazy, I cant resync on app.
> Anyone else maybe who can also help testing?

I was having the same problem had to unlink openhab, relink openhab to google home, for them to start working again. 

P.S. still getting "Sorry, I'm unable to reach X" when turning lights on, turning off works fine

**Comment by eeyepee** [comment] 2019-10-24 21:18
First I lost all my items in Google home. Then sync with openhab failed.
Now I synced with OH successfully but I have to re add the items back to
each Google home room.

The issue of ‘Sorry, Im unable...’ is still there

**Comment by kpanchen** [comment] 2019-10-24 22:20
> I ve applied one more deployment as there was a URL piece missing. Shall be back working, but my app is broken. Can you please help testing and let me know if the issue here is fixed?

No changes, "Cannot reach ...", did sync on devices.

**Comment by meingraham** [comment] 2019-10-24 22:23
There was a short period where GA was not able to reach openHAB. I can reach my devices again (I didn't have to reset or re-sync). However, the "Cannot reach..." problem when turning anything on remains.

**Comment by costascontis** [comment] 2019-10-25 06:05
also tested and the "Cannot reach..." issue remains.

**Comment by pythen** [comment] 2019-10-25 08:13
This is very annoying.
I don't have these problems in my installation.  

All my switches and devices works fine.

@marziman 
Can it be that the answer to Google is too slow in your cloud instance.

Snippet from logfile

Incoming request:
`Cloud function called:{"inputs":[{"context":{"locale_country":"DE","locale_language":"de"},"intent":"action.devices.EXECUTE","payload":{"commands":[{"devices":[{"customData":{"itemTag":"Switchable","itemType":"Switch","openhabVersion":"2.1"},"id":"Sound_OG_Media"}],"execution":[{"command":"action.devices.commands.OnOff","params":{"on":true}}]}]}}],"requestId":"16598702617570667355"}`

Logging method turnOnOff
'turnOnOff reqCommand:{"devices":[{"customData":{"itemTag":"Switchable","itemType":"Switch","openhabVersion":"2.1"},"id":"Sound_OG_Media"}],"execution":[{"command":"action.devices.commands.OnOff","params":{"on":true}}]}'

Response:
'turnOnOff done with result:{"requestId":"16598702617570667355","payload":{"commands":{"ids":["Sound_OG_Media"],"status":"SUCCESS","states":{"on":true,"online":true}}}}'

Execution time:

Function execution took 734 ms, finished with status code: 200

**Comment by eeyepee** [comment] 2019-10-25 09:48
Okay, seems interesting, so your command to google was to turn off/on one
device only and the incoming request was for two?

**Comment by michikrug** [comment] 2019-10-25 10:06
This seems true, there is no proper handling of multiple actions

**Comment by pythen** [comment] 2019-10-25 12:36
In my installation, I changed that now.
A single answer with all devices like the following log shows:

`turnOnOff done with result:{"requestId":"15882421122320353039","payload":{"commands":[{"ids":["Switch_OG_Hexen_2"],"status":"SUCCESS","states":{"on":false,"online":true}},{"ids":["Sound_OG_Media"],"status":"SUCCESS","states":{"on":false,"online":true}}]}}`

The answer from GA  is "I turn off two switches"

I'll do a commit later, I hope it helps.

**Comment by hotrodwinston** [comment] 2019-10-26 23:55
so is this fixed or not now for everyone?
mine worked fine on telling it to "turn off all lights" but haven't checked the routine yet. (It includes my security system and I don't wanna mess with it until bedtime.)

**Comment by kpanchen** [comment] 2019-10-26 23:57
> so is this fixed or not now for everyone?
No, turn off always worked fine, the problem is with on.

**Comment by kpanchen** [comment] 2019-10-27 00:00
I know this is wrong thread but while we are here just want to ask what's happening with thermostat support? It never worked but I don't see the thread related to that or at least conclusive thread, just want to confirm that it is not me doing something wrong and I will raise an issue to track it. Thanks!

**Comment by eeyepee** [comment] 2019-10-27 04:29
@Mehmet,
Since pythen has found a solution, any plans to test and upload at your
end?

**Comment by hotrodwinston** [comment] 2019-10-27 04:47
@kpanchen thermostat is another issue that is being worked on (can't remember the thread) but a quick fix for everything except setting mode is to remove all reference to homekit in the thermostat group. So anywhere it says homekit: remove it.

**Comment by kpanchen** [comment] 2019-10-27 06:52
> @kpanchen thermostat is another issue that is being worked on (can't remember the thread) but a quick fix for everything except setting mode is to remove all reference to homekit in the thermostat group. So anywhere it says homekit: remove it.

Yes, I know about that, it is basically like not specifying the tag at all. In this case google doesn't know about mode at all, hope we can set it right. Thanks for your reply, let's not hijack the thread, I'll wait for the fix!

**Comment by RayBa82** [comment] 2019-10-27 09:34
Do routines work without exceptions too, or why is this closed, because this thread is about routines, and not the error which occured just recently.

**Comment by eeyepee** [comment] 2019-10-27 09:56
The topic is subjected for routines but the issue seems to be mixed. I hope
both will be fixed soon.

**Comment by sriharsha-y** [comment] 2019-10-27 19:55
Hoping for the pull request to be merged asap. This is annoying me very much 🙁

**Comment by eeyepee** [comment] 2019-10-30 18:52
@marziman would you be kind and let us know regarding any plans to fix the problem?

**Comment by djmillsuk** [comment] 2019-10-31 12:24
i think im a little confused here but this is for the google assistant openHAB official linked service right? not a custom one? i hope its fixed soon or i might have to learn home assistant instead :'(. i cant handle always hearing that annoying error!

**Comment by bospiet** [comment] 2019-11-01 15:44
I have this issue too.  And so does a friend of mine.

**Comment by costascontis** [comment] 2019-11-03 18:26
> i think im a little confused here but this is for the google assistant openHAB official linked service right? not a custom one? i hope its fixed soon or i might have to learn home assistant instead :'(. i cant handle always hearing that annoying error!

i am little confused too ,am i looking at the right issue here?I and many others users of openhab/google assistant having this "Sorry,I'm unable to reach X" but i see here issue is closed!Is it fixed?Not for me at least.Do i need to update something???

**Comment by RestOp** [comment] 2019-11-03 18:45
> i think im a little confused here but this is for the google assistant openHAB official linked service right? not a custom one? i hope its fixed soon or i might have to learn home assistant instead :'(. i cant handle always hearing that annoying error!

I'm thinking right so about more then a year. By the way nothing happens, but more and more same posts here )))

**Comment by djmillsuk** [comment] 2019-11-03 20:28
I have moved to using the self hosted version here: https://github.com/gytisgreitai/openhab-google-home instead of the official open hab Google home link and now all my problems are gone :D

**Comment by marziman** [comment] 2019-11-03 21:03
Issue is closed since long, you guys keep writing. There is already a new update comminng with many reworks and great newdevices support. Just in the final review and soon to be rolled out. 
Feel always free to use your own installation.

Please do not use this closed issue, open a new one if really concerned
