### ISSUE TITLE
Ignore irrelevant tags

### ISSUE THREAD

**Issue by ahielg** [openhab/openhab-google-assistant#21] opened 2018-02-21 07:05 UTC
Looks like today if you have items with tags that are not known to this api the link process fails.
When using some openhab addons that uses tags (such as ImperiHome) you can not use this binding.

We should ignore unknown tags and not fail to link the account.

**Comment by skimdankish** [comment] 2018-02-21 19:01
It looks like the issue starts [here ](https://github.com/openhab/openhab-google-assistant/blob/b0596c0b0fa826d59a8df4849e7cea2192867ba2/functions/openhab.js#L493) since it may not "gracefully" ignore the object.  The function is probably still trying to examine.

Perhaps something earlier in the code to check if it's valid tag and break before the switch/case to go immediately to the next tag (this way it avoids erroneously processing the item).

**Comment by skimdankish** [comment] 2018-02-21 20:50
Check out [my commit / pull request](https://github.com/skimdankish/openhab-google-assistant/blob/612d4c57d5d54941ec5fd1ca76ede8f210c39cbd/functions/openhab.js#L522).  I have confirmed this breaks and throws back to the log that it was not added, one other issue is that I am seeing the ancillary tags (Fahrenheit, etc.) are also throwing back, but does not affect functionality.

**Comment by marziman** [comment] 2018-04-11 03:29
I will keep this open and https://github.com/openhab/openhab-google-assistant/pull/26 will help a little. Still going to deliver a better fix for this.

**Comment by skimdankish** [comment] 2018-05-06 15:25
@ahielg  

I could not replicate, I copied the same tag to my Lighting item.  Check your quotes! They look like the wrong style:

" = Good
“ = No Bueno!

**Comment by ahielg** [comment] 2018-05-06 17:01
@skimdankish
Switch sonos "Sonos" (gSonos)  ["Lighting"] 
Vs
Switch sonos "Sonos" (gSonos) ["Lighting", "iss:room:System", "iss:type:DevSwitch"]
Are you sure it is working?

**Comment by skimdankish** [comment] 2018-05-07 15:26
@ahielg 

AH! Ok, now it did it.  Strangely enough, when I remove the tagLoop/break it seems to work fine (even with nonsense or misspelled tags).

I might recommend to remove this in the next update.  Perhaps until then, just use one tag?? I know it's not ideal, but hopefully this will be resolved.

**Comment by ahielg** [comment] 2018-05-07 18:47
@skimdankish
I'm using those tags for imperihome app, maybe I'll duplicate the items....

**Comment by mgf909** [comment] 2018-05-10 21:48
@marziman - I also have this issue with multiple tags. I too use Imperihome binding. So would be great if this can be deployed to production asap so i can use Google Home again. ;-)
@skimdankish -Thanks for fixing!

**Closed** 2018-05-25 23:05 UTC

**Comment by ahielg** [comment] 2018-05-26 18:08
@skimdankish the latest deployment fix this issue!
Thanks all!

**Comment by skimdankish** [comment] 2018-05-26 18:10
Woohoo! glad to hear it's working.
